name: Build, Package & Notify

on:
  push:
    branches: [main]
    paths-ignore: ['README.md']
  pull_request:
    branches: [main]

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: '6.0.x'         # Must be defined at job level
      OUTPUT_PATH: 'bin/Release/net6.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish app
        run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}

      - id: upload_artifact
        name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build
          path: ${{ env.OUTPUT_PATH }}
          retention-days: 7

      - name: Send email with artifact info
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          secure: false    # Enables STARTTLS on port 587
          starttls: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Build Artifact Uploaded for Commit ${{ github.sha }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          content_type: text/html
          html_body: |
            <p>✅ Build succeeded and the artifact is ready!</p>
            <ul>
              <li><strong>Artifact:</strong> dotnet‑build</li>
              <li><strong>Path:</strong> ${{ env.OUTPUT_PATH }}</li>
              <li><strong>GitHub UI:</strong> <a href="https://${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View workflow run</a></li>
              <li><strong>Direct download:</strong> <a href="https://github.com/${{ github.repository }}/actions/artifacts/${{ steps.upload_artifact.outputs.artifact_id }}/zip?access_token=${{ secrets.PAT_TOKEN }}">Download ZIP (no login)</a></li>
            </ul>
          convert_markdown: false
